# Generated by Django 5.0.6 on 2024-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('reserved', 'Бронь'), ('sold', 'Куплено'), ('installment', 'Рассрочка'), ('barter', 'Бартер')], max_length=15)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('square_meters', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
